hiltonadmin/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from hiltonadmin import settings
from main import views as main
import private_storage.urls

admin.site.site_header = 'Administration - Student Dorm "Turmstraße 1"'

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path('nested_admin/', include('nested_admin.urls'), name="nested_admin"),
    path('association/', include('association.urls')),
    path('networking/', include('networking.urls')),
    path('game_rental/', include('game_rental.urls')),
    path('nordigen/', include('nordigen_app.urls')),
    path('user/', include('main.urls')),
    path('workinggroups/', include('workinggroups.urls')),
    path('statistics/', include('hilton_statistics.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('finances/', include('finances_v2.urls')),
    path('laundry_room/', include('laundry_room.urls')),

    re_path(r'^$', main.profile, name='profile'),
    re_path('^private-media/', include(private_storage.urls)),
    re_path(r'^', include('django_telegrambot.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

main/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from main import views

urlpatterns = [
    path('profile', views.profile, name='profile'),
    path('print', views.print, name='print'),
    path('job/<int:job_id>/delete', views.cancel_print, name='cancel_print'),
    path('logout_telegram', views.logout_telegram, name='logout_telegram'),
    path('tenant_list', views.tenant_list, name='tenant_list'),
    path('calendar', views.calendar, name='calendar'),
    path('calendar_remind/<int:is_social_service>/<int:event_id>/', views.calendar_remind, name='calendar_remind'),
    path('room_administration', views.room_administration, name='room_administration'),
    path('email', views.email, name='email'),
    path('no_permission', views.no_permission, name='no_permission'),
    path('telegram_groups', views.telegram_groups, name='telegram_groups'),
    path('login/', auth_views.LoginView.as_view(template_name='main/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='main/logout.html'), name='logout'),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(template_name='main/password_reset_form.html'),
        name='password_reset',
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='main/password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='main/password_reset_confirm.html'),
        name='password_reset_confirm',
    ),
    path(
        'reset_initial/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='main/password_reset_confirm_initial.html'),
        name='password_reset_confirm_initial',
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name='main/password_reset_complete.html'),
        name='password_reset_complete',
    ),
]

workinggroups/urls.py
from django.urls import path

from workinggroups import views

urlpatterns = [
    path('contacts/', views.contacts, name='contacts'),
]

workinggroups/models.py
from auditlog.registry import auditlog
from django.contrib.auth.models import Group
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.utils import timezone

from main.models import Person
from common.util.membership_validator import ensure_one_membership_at_any_time


class WorkingGroup(models.Model):
    group_django = models.ForeignKey(Group, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    email = models.CharField(max_length=250)
    should_attend_at_new_tenant_bar = models.BooleanField(default=False)
    first_leader_is_social_service = models.BooleanField(default=True)
    second_leader_is_social_service = models.BooleanField(default=False)
    members_can_be_active = models.BooleanField(default=False)
    members_are_active_by_default = models.BooleanField(default=False)
    is_mail_forwarding_sync_enabled = models.BooleanField(default=False, help_text="If enabled mails are forwarded to the working group leaders")

    group_membership = models.ManyToManyField(
        Person,
        through='GroupMembership',
    )

    def __str__(self):
        return self.name

    def is_member(self, person):
        return self.current_members().filter(person=person).exists()

    def current_members(self):
        return self.groupmembership_set.filter(
            Q(date_join__lte=timezone.now()) & (Q(date_leave__isnull=True) | Q(date_leave__gt=timezone.now())))

    def get_leaders(self):
        return self.current_members().filter(
            Q(type=GroupMembership.TYPE_FIRST_LEADER) | Q(type=GroupMembership.TYPE_SECOND_LEADER)).order_by(
            'type')

    def get_leader(self):
        return self.get_leaders().first()


class RoomKey(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    amount = models.SmallIntegerField()
    key_holder = models.ManyToManyField(
        Person,
        through='KeyHolder',
    )

    def __str__(self):
        return self.name


class GroupMembership(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    working_group = models.ForeignKey(WorkingGroup, on_delete=models.CASCADE)
    date_join = models.DateField(default=timezone.now)
    date_leave = models.DateField(blank=True, null=True)
    TYPE_FIRST_LEADER = '0'
    TYPE_SECOND_LEADER = '1'
    TYPE_MEMBER = '2'
    TYPES = (
        (TYPE_FIRST_LEADER, '1. Leader'),
        (TYPE_SECOND_LEADER, '2. Leader'),
        (TYPE_MEMBER, 'Member'),
    )
    type = models.CharField(max_length=2, choices=TYPES, default=0)
    comment = models.CharField(max_length=200, blank=True)
    mailing_list_enabled = models.BooleanField(default=True)

    def __str__(self):
        return self.person.full_name() + "_" + self.working_group.name

    @staticmethod
    def current_members():
        return GroupMembership.objects.filter(
            Q(date_join__lte=timezone.now()) & (Q(date_leave__isnull=True) | Q(date_leave__gte=timezone.now())))

    def clean(self):
        ensure_one_membership_at_any_time(self, GroupMembership.objects, Q(working_group=self.working_group))

    def is_active(self):
        """
        check if membership is running
        :return: true for active memberships
        """
        if self.date_leave is None:
            if self.date_join <= timezone.localdate():
                return True
            else:
                return False
        else:
            if self.date_leave > timezone.localdate():
                return True
            return False


class KeyHolder(models.Model):
    room_key = models.ForeignKey(RoomKey, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    amount_responsible_for = models.SmallIntegerField(default=1, blank=False, null=False)
    date_received = models.DateField()
    date_until = models.DateField(blank=True, null=True)
    internal = models.BooleanField(default=False, help_text="Wenn ein Schlüssel intern ausgegeben wurde und der Hausmeister dies nicht wissen soll.")

    def __str__(self):
        return self.person.full_name()

    @staticmethod
    def get_active_key_holders(when: timezone.datetime = timezone.now()):
        return KeyHolder.objects.filter(
            Q(date_received__lte=when) & (Q(date_until__isnull=True) | Q(date_until__gte=when)))

    def is_active(self) -> bool:
        """
        check if membership is running
        :return: true for active memberships
        """
        if self.date_until is None:
            if self.date_received <= timezone.localdate():
                return True
            else:
                return False
        else:
            if self.date_until > timezone.localdate():
                return True
            return False


@receiver(post_save, sender=GroupMembership, dispatch_uid="add_group_django")
def add_group_django(sender, instance, **kwargs):
    instance.person.user.groups.add(instance.working_group.group_django)
    instance.person.user.is_staff = True
    instance.person.user.save()
    # if he left the group he should not be a member anymore...
    if instance.date_leave and instance.date_leave <= timezone.localdate():
        instance.working_group.group_django.user_set.remove(instance.person.user)


@receiver(pre_delete, sender=GroupMembership, dispatch_uid='delete_group_django')
def delete_group_django(sender, instance, **kwargs):
    instance.working_group.group_django.user_set.remove(instance.person.user)
    print(instance.person.user.groups.all())
    if len(instance.person.user.groups.all()) == 0:
        instance.person.user.is_staff = False
        instance.person.user.save()


auditlog.register(WorkingGroup)
auditlog.register(RoomKey)
auditlog.register(GroupMembership)
auditlog.register(KeyHolder)

workinggroups/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Value, Max
from django.db.models.functions import Coalesce
from django.http import HttpResponse
from django.template import loader
from django.utils import timezone

from workinggroups.models import WorkingGroup


@login_required
def contacts(request):
    """
    Shows the contact people in an overview
    :param request:
    :return:
    """
    working_groups = WorkingGroup.objects.all()
    today = timezone.localdate()
    for working_group in working_groups:
        working_group.memberships = working_group.current_members().order_by('type') \
            .select_related("person").prefetch_related("person__user").annotate(
            room=Coalesce(Max("person__tenant__room__number", filter=Q(person__tenant__date_move_in__lte=today, person__tenant__date_move_out__gte=today)),
                          Value("extern")))
    template = loader.get_template('workinggroups/contact_people.html')
    context = {
        'title': 'Contacts',
        'workinggroups': working_groups,
    }

    return HttpResponse(template.render(context, request))

workinggroups/templates/workinggroups/contact_people.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load djmoney %}



{% block content %}
    <div class="row">
        <div class="col 12">
            <div class="p-3 mb-4 bg-light rounded-3">
                <div class="container-fluid py-5">
                    <h1 class="display-4">Questions or Issues?</h1>
                    <p class="lead">Below you will find a list containing all contacts
                        categorized in working
                        groups.</p>
                    <hr class="my-4">
                    <p>If you want to help and contribute feel free to send an email
                        to
                        the corresponding email
                        address.</p>
                </div>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col 12">
            <div id="workinggroups-accordion" class="accordion">
                {{ workinggroup.memberships }}
                {% for workinggroup in workinggroups %}
                    <div class="accordion-item">
                        <div id="heading-{{ workinggroup.id }}"
                             class="accordion-header">
                            <button class="accordion-button collapsed" type="button"
                                    data-bs-toggle="collapse"
                                    data-bs-target="#collapse-{{ workinggroup.id }}"
                                    aria-expanded="false"
                                    aria-controls="{{ workinggroup.id }}">
                                {{ workinggroup.name }}
                            </button>
                        </div>
                        <div id="collapse-{{ workinggroup.id }}"
                             class="accordion-collapse collapse"
                             aria-labelledby="heading-{{ workinggroup.id }}"
                             data-bs-parent="#workinggroups-accordion">
                            <div class="accordion-body">
                                {{ workinggroup.description }} <br><br>
                                <span data-feather="mail"></span>&nbsp;{{ workinggroup.email }}
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col">Type</th>
                                        <th scope="col">Name</th>
                                        <th scope="col">Room</th>
                                        <th scope="col">Comment</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for member in workinggroup.memberships %}
                                        <tr>
                                            <th scope="row">{{ member.get_type_display }}</th>
                                            <td>{{ member.person }}</td>
                                            <td>{{ member.room }}</td>
                                            <td>{{ member.comment }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <script>
        // automatically open the accordion that is selected by the anchor/hash
        function openAnchorAccordion() {
            if (window.location.hash) {
                const target = $('body').find(window.location.hash);
                const targetAccordion = target.find('.collapse');
                if (targetAccordion) {
                    targetAccordion.collapse('show');
                }
            }
        }

        openAnchorAccordion();
    </script>
{% endblock %}